---
Title: "Introduction"
Weight: 10
---

:imagesdir: ./../../images/en/user

= Introducción

== El equipo de SuiteCRM y la comunidad
 
Es seguro decir que sin el trabajo constante del Equipo de SuiteCRM y la Comunidad, no habría tenido el impulso y el compromiso de sentarme y escribir esta guía del usuario. Nuevas funcionalidades y mejoras en el producto central se agregan constantemente para hacer que SuiteCRM sea el mejor producto Open Source CRM del mundo, y para competir con proveedores de CRM propietarios como SugarCRM, Salesforce y Microsoft.

En cuanto a la Comunidad SuiteCRM, proporcionan informes de errores, correcciones de errores y pruebas de errores. La comunidad está en el corazón de cualquier proyecto de código abierto y esto no es diferente con SuiteCRM. Con cada nuevo lanzamiento, la comunidad crece y con ella aumentan los beneficios del ecosistema de código abierto.

== ¿Qué es SuiteCRM?
 
SuiteCRM es un software fork del popular https://en.wikipedia.org/wiki/Customer_relationship_management[Sistema de gestión de relaciones con el cliente] (CRM) https://en.wikipedia.org/wiki/SugarCRM[SugarCRM], desarrollado y mantenido por SalesAgility. Es una aplicación alternativa de código abierto y gratuito. Fue lanzado el 21 de octubre de 2013 como la versión 7.0. La versión de producción más reciente al momento de publicar esta Guía del usuario es SuiteCRM 7.6.3. 27

SuiteCRM se ha descargado más de 500,000 veces desde el original lanzamiento. Ha sido adoptado por NHS (Servicio Nacional de Salud) de Inglaterra Código para el programa de salud que busca fomentar el código abierto en el NHS en Inglaterra.
The SuiteCRM project has stated that the every line of code released by the project will be open source. SuiteCRM project is intended to be an enterprise-class open source alternative to proprietary products.

Está disponible una Hoja de ruta del proyecto que detalla las mejoras planificadas.

Un foro de apoyo público activo con más de 25,000 miembros es
disponible para soporte gratuito y es regularmente monitoreado y actualizado por
Equipo de proyecto.

Un directorio de extensiones está disponible donde tanto gratis como de pago
las mejoras están disponibles.

El proyecto mantiene https://suitecrmondemand.com/[SuiteCRM:OnDemand],
una instalación de Software As A Service para usuarios que buscan una implementación rápida
y servicio libre de mantenimiento.

No habrá software con licencia como parte del proyecto administrado por
SalesAgility. Todo el código es gratis. Todo el código está disponible gratis
descargar. No hay una agenda oculta para cobrar por el acceso al código. Eso
es y siempre será libre y de código abierto. No habrá pago por
versiones.

== ¿Quién es SalesAgility?
 

SalesAgility es una consultoría de código abierto acreditada por ISO centrada en
Customer Relationship Management (CRM). Uno de los primeros en adoptar SugarCRM
Community Edition, SalesAgility son los creadores y mantenedores detrás
la horquilla SugarCRM - SuiteCRM.

SalesAgility ha entregado más de 300 SuiteCRM y SugarCRM
proyectos, y son conocidos como un conocimiento y experiencia de clase mundial
recurso para CRM de fuente abierta. Los clientes incluyen gobiernos, empresas
y pequeñas y medianas empresas en todo el mundo.

SalesAgility tiene una declaración de misión clara:

[quote]
Nuestro objetivo es innovar y proporcionar soluciones avanzadas de SuiteCRM junto con el servicio al cliente líder de la industria y soporte.

[quote]
Creemos que el código abierto es lo mejor para nuestros clientes y continuaremos construyendo, innovando, evangelizando y brindando lo mejor practicar modelos de trabajo para la comunidad de código abierto.

== ¿Qué hay en la guía del usuario?


La Guía del usuario de SuiteCRM se ha escrito para el usuario final. Esta guíacubre el viaje de usuario de SuiteCRM de extremo a extremo. Exploraremos todas las áreas desde los conceptos básicos de iniciar sesión en el sistema para crear complejos flujos de trabajo automatizados e informes.La Guía del usuario de SuiteCRM está dividida en varios capítulos. Estos capítulos están ordenados para que progreses a través de tu guía como lo harías lógicamente en el uso cotidiano de CRM. Los capítulos contienen subsecciones que derribar barreras para usted, explicando cómo optimizar el uso del sistema de gestión de relaciones con los clientes para gestionar ventas de manera efectiva.Los lectores de la Guía del usuario de SuiteCRM no necesitan tener conocimiento de programador o conocimiento previo de SuiteCRM. Se aconsejan conocimientos de informática, que está familiarizado con el uso de su web elegida navegador y ese SuiteCRM ya se ha instalado y configurado.
