---
Title: "Introducción"
Weight: 10
---

:imagesdir: /images/es/user

= Introducción

== El equipo y la comunidad de SuiteCRM
 

Es seguro decir que sin el trabajo constante del equipo de SuiteCRM y la comunidad, no habría tenido la motivación y el compromiso de sentarme y escribir esta guía del usuario. 
Nuevas funcionalidades y mejoras en el núcleo son constantemente añadidos para hacer de SuiteCRM el mejor CRM Open Source
en el mundo, y competir con proveedores de CRM propietarios como
como SugarCRM, Salesforce y Microsoft.

En cuanto a la comunidad SuiteCRM - que proporcionan informes de errores, correcciones de errores y pruebas de fallos. La Comunidad está en el corazón de cualquier proyecto de Código Abierto y esto no es diferente con SuiteCRM. Con cada nueva versión, el la comunidad crece y con ella crecen los beneficios del Open Source
ecosistema.

== ¿Qué es SuiteCRM?
 

SuiteCRM es una bifurcación de software de la popular
https://en.wikipedia.org/wiki/Customer_relationship_management[Cliente
Sistema de gestión de relaciones] (CRM)
https://en.wikipedia.org/wiki/SugarCRM[SugarCRM], desarrollado y
mantenido por SalesAgility. Es una alternativa libre y de código abierto
aplicación. Fue lanzado el 21 de octubre de 2013 como versión 7.0. El
La última versión de producción en el momento de la publicación de esta Guía del usuario es
SuiteCRM 7.6.3.

SuiteCRM ha sido descargado más de 500.000 veces desde la versión original.
liberación. Ha sido adoptado por el Servicio Nacional de Salud (NHS) de Inglaterra.
Código para el programa de Salud que busca fomentar el código abierto en el NHS
en Inglaterra.

El proyecto SuiteCRM ha declarado que todas las líneas de código liberadas por
el proyecto será de código abierto. El proyecto SuiteCRM está destinado a ser un
una alternativa de código abierto de clase empresarial a los productos patentados.

Existe una hoja de ruta del proyecto que detalla las mejoras planificadas.

Un foro de apoyo público activo con más de 25.000 miembros es
disponible para soporte gratuito y es monitoreado y actualizado regularmente por el
Equipo del proyecto.

Un directorio de extensiones está disponible donde tanto las gratuitas como las de pago
hay mejoras disponibles.

El proyecto mantiene https://suitecrmondemand.com/[SuiteCRM:OnDemand],
una instalación de Software As A Service para usuarios que buscan una implementación rápida
y servicio sin mantenimiento.

No habrá ningún software con licencia como parte del proyecto gestionado por
Agilidad de ventas. Todo el código es gratuito. Todo el código está disponible gratuitamente
descarga. No hay una agenda oculta para cobrar por el acceso al código. Se
es y siempre será libre y de código abierto. No habrá ningún pago
versiones.

== ¿Quién es SalesAgility?
 

SalesAgility es una consultoría de código abierto acreditada por la ISO que se centra en
Gestión de las relaciones con los clientes (CRM). Una de las primeras empresas en adoptar SugarCRM
Community Edition, SalesAgility son los creadores y mantenedores detrás de
la horquilla SugarCRM - SuiteCRM.

SalesAgility ha entregado más de 300 SuiteCRM y SugarCRM
proyectos, y son conocidos como un conocimiento y experiencia de clase mundial
recurso para CRM de código abierto. Entre sus clientes se incluyen gobiernos, empresas
y las pequeñas y medianas empresas a nivel mundial.

SalesAgility tiene una declaración de misión clara:

[cita]
Nuestro objetivo es innovar y ofrecer soluciones avanzadas de SuiteCRM
junto con el servicio de atención al cliente líder de la industria, y
apoyo.

[cita]
Creemos que el código abierto es lo mejor para nuestros clientes y
seguiremos construyendo, innovando, evangelizando y proporcionando las mejores
practicar modelos de trabajo para la comunidad de código abierto.

== ¿Qué hay en la Guía del usuario?

La Guía del usuario de SuiteCRM ha sido escrita para el usuario final. Esta guía
cubre el viaje del usuario de SuiteCRM de principio a fin. Exploraremos todos
áreas desde lo básico de la conexión al sistema hasta la creación de sistemas complejos.
flujos de trabajo e informes automatizados.

La Guía del usuario de SuiteCRM está dividida en varios capítulos. Estos capítulos
se ordenan para que progreses a través de tu guía como lo harías
de forma lógica en el uso diario de CRM. Los capítulos contienen subsecciones que
romper las barreras para usted, explicándole cómo optimizar el uso del
sistema de gestión de las relaciones con los clientes para gestionar eficazmente las ventas
datos.

Los lectores de la Guía del Usuario de SuiteCRM no necesitan tener desarrollo
conocimiento o conocimiento previo de SuiteCRM. Se aconseja que usted sea
con conocimientos de informática, que usted está familiarizado con el uso de la web de su elección
y que SuiteCRM ya ha sido instalado y configurado.


Traducción realizada con la versión gratuita del traductor www.DeepL.com/Translator
